https://docs.transonline.org.cn/files/SOC-V7.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/SOC-V7.pdf
  snippet: WPATH SOC V7
  title: WPATH SOC V7
https://docs.transonline.org.cn/files/SOC-V8-CN.pdf:
  is_related: duplicate
  link: https://docs.transonline.org.cn/files/SOC-V8-CN.pdf
  snippet: WPATH SOC V8 (翻译版)
  title: WPATH SOC V8 (翻译版)
https://docs.transonline.org.cn/files/The_Case_Against_Autogynephilia%20-%20译文.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/The_Case_Against_Autogynephilia%20-%20译文.pdf
  snippet: The Case Against Autogynephilia
  title: The Case Against Autogynephilia
https://docs.transonline.org.cn/files/Transgender_ABC.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/Transgender_ABC.pdf
  snippet: 跨性别ABC
  title: 跨性别ABC
https://docs.transonline.org.cn/files/UNDP-CH-亚太跨性别健康蓝图.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/UNDP-CH-亚太跨性别健康蓝图.pdf
  snippet: 亚太跨性别健康蓝图
  title: 亚太跨性别健康蓝图
https://docs.transonline.org.cn/files/endocrine-society-guidelines.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/endocrine-society-guidelines.pdf
  snippet: 内分泌协会指南(2017)
  title: 内分泌协会指南(2017)
https://docs.transonline.org.cn/files/guidebook_for_musle_injections.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/guidebook_for_musle_injections.pdf
  snippet: 跨性别：肌肉注射指南
  title: 跨性别：肌肉注射指南
https://docs.transonline.org.cn/files/shi-fei-nan-nv-1.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/shi-fei-nan-nv-1.pdf
  snippet: '[TGR]是非男女-1'
  title: 是非男女-1
https://docs.transonline.org.cn/files/shi-fei-nan-nv-2.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/shi-fei-nan-nv-2.pdf
  snippet: '[TGR]是非男女-2'
  title: 是非男女-2
https://docs.transonline.org.cn/files/shi-fei-nan-nv-3.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/shi-fei-nan-nv-3.pdf
  snippet: '[TGR]是非男女-3'
  title: 是非男女-3
https://docs.transonline.org.cn/files/ucsf.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/ucsf.pdf
  snippet: UCSF指南
  title: UCSF指南
https://docs.transonline.org.cn/files/跨性别者性别认同的法律承认.pdf:
  is_related: 'true'
  link: https://docs.transonline.org.cn/files/跨性别者性别认同的法律承认.pdf
  snippet: 跨性别者性别认同的法律承认
  title: 跨性别者性别认同的法律承认
https://docs.transonline.org.cn/files/跨性别证件修改手册.pdf:
  is_related: duplicate
  link: https://docs.transonline.org.cn/files/跨性别证件修改手册.pdf
  snippet: 跨性别证件修改手册
  title: 跨性别证件修改手册
