.:
  name: .
  description: 根目录，按照内容与来源分类
news-website:
  name: news-website
  description: 根目录，按照内容与来源分类
news-website/中国新闻网:
  name: 中国新闻网
  description: 本目录收录了与跨性别相关的一系列新闻报道和个人故事，涉及跨性别者在军事服役、法律政策、以及自身经历和社会接受度等方面的内容。这些资料展现了跨性别者在社会中的挑战与奋斗，也记录了相关政策的变化和影响。
news-website/凤凰网:
  name: 凤凰网
  description: 凤凰网收录了一系列跨性别相关的文章和资讯，涵盖了文化、娱乐、时尚、金融及心理等多个领域，探讨了跨性别者的生活经历、社会挑战、以及对性别认同的深入思考。这些内容反映了跨性别群体的多样性与面临的社会问题，旨在提升公众对跨性别事务的理解与接纳。
news-website/搜狐新闻:
  name: 搜狐新闻
  description: 这是搜狐新闻中收录的一系列与跨性别相关的文章和报道，内容涵盖了跨性别者的生活故事、社会现状、时尚领域的表现以及医疗经验分享等，旨在为公众提供一个多维度了解跨性别群体的平台。
news-website/新浪新闻:
  name: 新浪新闻
  description: 此目录包含与跨性别相关的内容，涵盖变装文化、跨性别者自述、法律政策和社会环境影响等多个方面。内容包括变装活动、跨性别者的生活体验、以及对跨性别群体的社会态度等深入探讨，旨在为公众提供全面的跨性别信息与知识。
news-website/澎湃新闻:
  name: 澎湃新闻
  description: 澎湃新闻目录中包含了多个与跨性别相关的案例报道及社会问题探讨，涵盖了个人生活故事、变性手术带来的法律与社会挑战、跨性别人士遭遇的歧视等。这些内容不仅反映了跨性别群体的生存现状，也为公众提供了有关跨性别者的医疗资源、心理健康、法律政策的深入了解。
news-website/网易新闻:
  name: 网易新闻
  description: 该目录包含了与跨性别相关的新闻与讨论，涵盖变性手术、公众认同、性别认同教育、文化表达等方方面面的内容。这些信息能够帮助公众更好地理解跨性别者的生活与挑战。
news-website/腾讯新闻:
  name: 腾讯新闻
  description: 本目录收录了与跨性别相关的新闻报道，涵盖了跨性别人士的生活故事、社会支持、医疗资源、法律政策以及文化表达等多方面内容，为用户提供了多维度的信息视角，帮助了解跨性别群体在社会中的现状与挑战。
学术文献:
  name: 学术文献
  description: 此目录包含关于跨性别议题的学术文献，包括人文、医学、法律和社会科学领域的研究和资料，包括但不限于发表于学术期刊的论文和由大学附属出版社出版的学术书籍。采用近似于学术写作的风格创作、发布于某些期刊杂志，但不确定是否为「学术」文献的，放置于「杂志及新闻报道」分类。
学术文献/人文社科:
  name: 人文社科
  description: 该目录下收录了与跨性别相关的社会科学研究文献，包括对跨性别群体的社会分析、文化研究以及相关的理论探讨。这些文献旨在提升对跨性别群体生活现状的理解与关注。
学术文献/医学:
  name: 医学
  description: 本目录收录了与跨性别相关的医学领域的学术文献，包括医疗资源、医学研究以及跨性别个体的医疗经验分享等内容。这些文献为探索和理解跨性别者在医疗过程中的需求和挑战提供了宝贵的资料。
学术文献/法律:
  name: 法律
  description: 本目录收录与跨性别者相关的法律政策与社会环境的学术文献，涵盖法律法规、案例分析及社会影响等内容，旨在为研究提供重要的背景资料和理论支持。
政府及官方组织文件:
  name: 政府及官方组织文件
  description: 本目录收录了与跨性别相关的政府及官方组织文件，包括中国大陆、加拿大、港澳台、美国以及联合国等地区和组织的相关政策和文件。「官方组织」指拥有接近「政府」地位和影响力，但不属于「政府」的国际性组织，在本版块中只指代联合国及其下属机构。这些资料为跨性别群体提供了法律政策、社会环境的背景信息，帮助人们理解不同地区的现状和对跨性别者的支持程度。
政府及官方组织文件/中国大陆:
  name: 中国大陆
  description: 该目录包含与中国大陆政府及官方组织相关的跨性别法律文件和政策资料。提供各种宣传资料、政府报告及法律文书，有助于深入了解国家法律政策对跨性别群体的影响和支持。
政府及官方组织文件/其他地区:
  name: 其他地区
  description: 该目录包含与跨性别政策和法律相关的政府及官方组织文件，旨在为跨性别者提供合法权益方面的指导和支持，特别是在其他地区的实施情况和伴侣制度的适用性。
政府及官方组织文件/加拿大:
  name: 加拿大
  description: 本目录收录有关加拿大的政府及官方组织对跨性别者的政策、法律及其相关文件，旨在提供关于跨性别者权益保障、健康医疗服务以及社会支持等方面的官方信息和资源。
政府及官方组织文件/港澳台:
  name: 港澳台
  description: 该目录收录了关于港澳台地区政府及官方组织发布的与跨性别相关的文件和信息，涉及相关政策、法律和社会环境的内容。这些文件旨在提供更清晰的法律框架和社会支持，以促进跨性别群体的权益。
政府及官方组织文件/美国:
  name: 美国
  description: 本目录收录了来自美国的政府及官方组织关于跨性别相关政策和法律的文件，旨在提供对跨性别者权益和法律保护的官方信息和指南。
政府及官方组织文件/联合国:
  name: 联合国
  description: 本目录收录了与联合国相关的官方文件，旨在提供跨性别人士在全球范围内受到的法律保护和人权关注的资讯。这些文件将有助于了解各国在跨性别相关议题上的政策和承诺。
文学作品和艺术创作:
  name: 文学作品和艺术创作
  description: 本部分收录一切形式的跨儿文学艺术创作。无论是发布于互联网某个阴暗角落的「变性人」自传，还是形式晦涩、发人深省的诗歌电影，均可收录在本版块。，涵盖了多种形式的表达，包括小说、漫画、纪实作品、自传和诗歌等。
文学作品和艺术创作/图像:
  name: 图像
  description: 该目录收录了与跨性别主题相关的摄影、绘画等图片作品。
文学作品和艺术创作/小说:
  name: 小说
  description: 本目录收录与跨性别相关的小说作品，涵盖了跨性别者的生活经历、情感纠葛及自我认同等主题。作品通过文学的方式，表达了跨性别者的独特声音与故事，旨在提高社会对这一群体的理解与关注。
文学作品和艺术创作/漫画:
  name: 漫画
  description: 本目录收录与跨性别主题相关的漫画作品，涵盖多样化的故事情节和艺术风格，旨在通过视觉艺术表达跨性别者的生活、感受与经历。
文学作品和艺术创作/纪实作品:
  name: 纪实作品
  description: 该目录收录与跨性别相关的纪实作品，展现跨性别者的真实生活与经历。这些作品不仅反映了个人故事，还呈现了对于社会现象的深刻洞察，包括对身份认同、过渡过程及社会接受度等话题的探索。
文学作品和艺术创作/自传:
  name: 自传
  description: 该目录收录与跨性别相关的自传性文学作品，展示跨性别者的生命故事与过渡经历。自传不仅反映个人的成长与探索，还记录了在社会环境中的真实挑战与心路历程，具有重要的文学价值和社会意义。
文学作品和艺术创作/诗歌:
  name: 诗歌
  description: 本目录收录与跨性别主题相关的诗歌作品，旨在通过文学的方式表达跨性别人群的内心世界与情感历程。这些作品反映了跨性别个体在社会、文化背景下的经历和感受，展示了多样的艺术表现形式。
文学作品和艺术创作/音频影像:
  name: 音频影像
  description: 本目录收录了与跨性别相关的音频影像作品，包括艺术中心与国际美术馆合作的项目。这些作品展示了跨性别艺术家的创作，反映了其独特的视角和经历。
杂志及新闻报道:
  name: 杂志及新闻报道
  description: 本目录包含关于中国大陆、海外及港澳台地区的跨性别相关杂志与新闻报道，二级分类按照发布的报纸杂志所在地区区分。旨在汇集各地对跨性别话题的不同视角与声音，提供相关信息和资源。
杂志及新闻报道/中国大陆:
  name: 中国大陆
  description: 这一目录收录了来自中国大陆的杂志和新闻报道，涵盖了跨性别群体的各种生活与社会现象，提供了真实的视角和声音，展示了跨性别者在社会中所面临的挑战与成就。
杂志及新闻报道/海外:
  name: 海外
  description: 此目录包含与跨性别相关的国际杂志和新闻报道，旨在分享海外跨性别群体的生活、挑战和成就。这些报道和文章提供了宝贵的视角，加深公众对跨性别议题的理解，促进社会包容。
杂志及新闻报道/港澳台:
  name: 港澳台
  description: 本目录收录与港澳台地区相关的跨性别报道与杂志内容，包括对跨性别者的生活、法律、医疗等多方面的报道，旨在宣传和提高社会对跨性别问题的认知与理解。
社群及NGO文件:
  name: 社群及NGO文件
  description: 本部分可收录的内容较为广泛。无论是如北京同志中心、同语这样的 NGO 出具的调查报告、教程指南，还是跨儿社群某论坛上由志愿者写作的 HRT
    指南、出柜指南等，甚至是涉及色情内容的「女装」或自我探索类教程，均可收录在本版块内。这一目录也包括各类医疗体系、学校和社群的相关资料。这些信息有助于了解支持跨性别人士的组织资源及环境。
社群及NGO文件/其他组织文件:
  name: 其他组织文件
  description: 这一目录包含关于跨性别群体的统计报告和资料指南，旨在提供有效的资源和数据支持，帮助人们更好地理解和关注跨性别群体的需求与现状。
社群及NGO文件/医院和医疗体系:
  name: 医院和医疗体系
  description: 此目录收录了与跨性别相关的医院及医疗体系信息，例如医疗资源、医院政策及医疗经验分享等。这些资料可帮助跨性别者了解医疗服务的可获得性和具体体验。
社群及NGO文件/学校:
  name: 学校
  description: 该目录包含与学校及教育相关的跨性别社群和非政府组织的文件。这些文件可能涵盖学校内的支持资源、跨性别学生的权益保护信息、教育政策的变革等内容，以推动对跨性别群体的理解和接纳。
社群及NGO文件/手册指南:
  name: 手册指南
  description: 该目录包含跨性别相关的非政府组织（NGO）资料指南，旨在为社区成员提供资源和支持，帮助他们了解可用的服务与信息。
社群及NGO文件/社群讨论:
  name: 社群讨论
  description: 该目录包含了与跨性别社群相关的组织和非政府组织（NGO）的信息，包括中国大陆及海外的社群动态和资源。
社群及NGO文件/统计报告:
  name: 统计报告
  description: 此目录包含与跨性别群体相关的统计报告，为研究人员和政策制定者提供有关跨性别者生存现状和需求的数据支持。这些报告致力于反映跨性别者在社会中的真实情况，包括人口统计、健康状况和社会接纳度等方面的信息。
