name: ''
description: 跨性别与多元性别档案馆包含如下内容：
curator: ''
source: ''
tags:
- 学术文献
- 跨性别
- 多元性别
- 文学艺术
- 社会政策
- 数据统计
- 公共资源
- 社区支持
license: ''
files: []
subdirs:
- 学术文献
- 政府及官方组织文件
- 文学作品和艺术创作
- 杂志及新闻报道
- 社群及NGO文件
