name: 中国大陆
description: 该目录包含与中国大陆政府及官方组织相关的跨性别法律文件和政策资料。提供各种宣传资料、政府报告及法律文书，有助于深入了解国家法律政策对跨性别群体的影响和支持。
curator: ''
source: ''
tags:
- 法律政策
- 政府文件
- 中国大陆
- 跨性别
- 官方资料
license: ''
files:
- name: G05_性别重置技术临床应用管理规范
  filename: G05_性别重置技术临床应用管理规范.pdf
  type: document
  format: PDF Document
  size: 746449
  md5: c21f01d4ca58541cb10d2e965ea73a5d
  page: G05_性别重置技术临床应用管理规范_page.md
- name: PDF_先天性结构畸形救助项目(2021年版)
  filename: PDF_先天性结构畸形救助项目(2021年版).pdf
  type: document
  format: PDF Document
  size: 4279230
  md5: 629ba870448d274ab34cb4484bcc1a81
  page: PDF_先天性结构畸形救助项目(2021年版)_page.md
- name: PDF_附件_2021年国家级继续医学教育项目表
  filename: PDF_附件_2021年国家级继续医学教育项目表.pdf
  type: document
  format: PDF Document
  size: 2884702
  md5: 5d67f33724879db341ad3903bde0fe05
  page: PDF_附件_2021年国家级继续医学教育项目表_page.md
- name: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知
  filename: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知.pdf
  type: document
  format: PDF Document
  size: 846716
  md5: f65e050584da608371edf3c7f8141b79
  page: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知_page.md
- name: 变性手术技术管理规范征求意见稿_便函_2009
  filename: 变性手术技术管理规范征求意见稿_便函_2009.pdf
  type: document
  format: PDF Document
  size: 466420
  md5: 3dea8d62c04b66060c8afbaf4febffa0
  page: 变性手术技术管理规范征求意见稿_便函_2009_page.md
- name: 国家限制类技术目录2022_年版
  filename: 国家限制类技术目录2022_年版.pdf
  type: document
  format: PDF Document
  size: 207409
  md5: 8e00050c2184796a5128c76b5e1616a0
  page: 国家限制类技术目录2022_年版_page.md
- name: 性别变更更正办理服务指南
  filename: 性别变更更正办理服务指南.pdf
  type: document
  format: PDF Document
  size: 134382
  md5: 999c6055a38b260861819b3787d59385
  page: 性别变更更正办理服务指南_page.md
- name: 户籍管理领域基层政务公开标准目录
  filename: 户籍管理领域基层政务公开标准目录.pdf
  type: document
  format: PDF Document
  size: 209839
  md5: ea9b84b452f3320a701119ed085ded81
  page: 户籍管理领域基层政务公开标准目录_page.md
- name: 第二部分整形外科专科医师规范化培训细则试行
  filename: 第二部分整形外科专科医师规范化培训细则试行.pdf
  type: document
  format: PDF Document
  size: 315632
  md5: 8fd1d6e46c79e4f940d2add346720740
  page: 第二部分整形外科专科医师规范化培训细则试行_page.md
subdirs: []
