site_name: 跨与多元性别档案
repo_url: https://github.com/project-polymorph/trans-digital-cn
site_url: https://digital.transchinese.org/
edit_uri: https://github.com/project-polymorph/trans-digital-cn/edit/main/
site_description: '本存档库包含各类跨性别、多元性别、酷儿相关的文档，包括学术文献、社群报告、文学作品、杂志与报纸、政府文件等。'
site_author: 多元性别中文数字图书馆
copyright: '多元性别中文数字图书馆 2025'
theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.path
    - navigation.top
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: zh
plugins:
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
  # - rss:
  #     match_path: ".*"
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated
  # - git-authors
  # - git-revision-date-localized:
  #     enable_creation_date: true
extra:
  analytics:
    provider: google
    property: G-C3BBZBZSV8
  social:
  - icon: /fontawesome/regular/envelope
    name: send me an email
    link: mailto:admin@transchinese.org
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/transchineseorg
  extra:
    homepage: https://transchinese.org
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
