name: 知乎
description: 本目录汇集了来自知乎平台的多篇关于中国大陆多元性别群体的社群讨论文档。
curator: ''
source: ''
tags:
- 多元性别
- 跨性别
- 酷儿
- 社群讨论
- 知乎
- 中国大陆
- 医疗资源
- 过渡经历
- 法律政策
- 社会环境
license: ''
files:
- name: zhihu1
  filename: zhihu1.jpg
  type: image
  format: JPEG Image
  size: 241325
  md5: ce107543be2d69f8a03ed70dd7d26dd7
  page: zhihu1.jpg
- name: zhihu2
  filename: zhihu2.jpg
  type: image
  format: JPEG Image
  size: 43244
  md5: 13d3c648a558f3fd63a70ca1064be80e
  page: zhihu2.jpg
- name: zhihu3
  filename: zhihu3.jpg
  type: image
  format: JPEG Image
  size: 234348
  md5: 739ebfcf7b6eac8b3111e1f5c880cce0
  page: zhihu3.jpg
subdirs: []
